# Generated by Django 2.2.3 on 2019-10-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchr_app', '0002_auto_20191008_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='views',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='date_last_searched',
        ),
        migrations.AddField(
            model_name='keyword',
            name='date_last_searched',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
