# Generated by Django 2.2.3 on 2019-10-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchr_app', '0003_auto_20191008_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='date_last_searched',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
