# Generated by Django 2.2.3 on 2019-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchr_app', '0005_auto_20191008_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='date_last_searched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
