# Generated by Django 2.2.3 on 2019-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchr_app', '0006_auto_20191009_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='first_searched_date',
            field=models.DateTimeField(default='1970-01-01 00:00'),
            preserve_default=False,
        ),
    ]
